name: Run-Daily

on:
  schedule:
    - cron: '30 21 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 

    - name: Generate the files
      run: |
        python3 fr.py -o out
